"" General
set relativenumber " Show line numbers
set showmatch " Highlight matching brace
set visualbell " Use visual bell (no beeping)
 
set hlsearch " Highlight all search results
set smartcase " Enable smart-case search
set ignorecase " Always case-insensitive
set incsearch " Searches for strings incrementally
 
set autoindent " Auto-indent new lines
set expandtab " Use spaces instead of tabs
set shiftwidth=4 " Number of auto-indent spaces
set smartindent " Enable smart-indent
set smarttab " Enable smart-tabs
set softtabstop=4 " Number of spaces per Tab
set tabstop=4

"" Advanced
set ruler " Show row and column ruler information
 
set undolevels=1000 " Number of undo levels
set backspace=indent,eol,start " Backspace behaviour
 
 
"" Generated by VimConfig.com

set mouse=a
syntax on
execute pathogen#infect()
filetype plugin indent on

"" Window
map <C-Up> <C-w><Up>
map <C-Down> <C-w><Down>
map <C-Left> <C-w><Left>
map <C-Right> <C-w><Right>

"" HTML
autocmd BufRead,BufNewFile *.html.erb set filetype=html
autocmd filetype html inoremap <C-t> <ESC>viwxa<<ESC>pa><ESC>oa<BS><ESC>o<ESC>a</<ESC>pa><ESC><Up>a
autocmd filetype html inoremap <C-g> <ESC>viwxa<<ESC>pa></<ESC>pa><ESC>Bf>a

"" Latex
autocmd BufRead,BufNewFile *.tex set filetype=tex
autocmd filetype tex inoremap <F5> <ESC>:!pdflatex<space>%<Enter>a
autocmd filetype tex noremap <F5> :!pdflatex<space>%<Enter>
autocmd filetype tex inoremap <S-F5> <ESC>:!pdflatex<space>%<Enter>a:!zathura<space>%<.pdf&<Enter>
autocmd filetype tex noremap <S-F5> :!pdflatex<space>%<Enter>:!zathura<space>%<.pdf&<Enter>
autocmd filetype tex inoremap <C-e> <ESC>viwxa\begin{<ESC>pa}<ESC>o<ESC>o<ESC>a\end{<ESC>pa}<ESC><Up>a
autocmd filetype tex inoremap <C-b> \textbf{}<++><ESC>4hi
autocmd filetype tex inoremap <Space><Tab> <Esc>/<++><Enter>da<a


